server.port=8090

spring.application.name=spring-service

# local defaults - overwriten by CI/CD variables
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass
spring.datasource.driver-class-name=org.postgresql.Driver