name: Spring Service
run-name: Deploy ${{ github.ref_name }} to ${{ github.event.inputs.environment || 'test' }}

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: test
      action:
        description: "Choose what to do"
        required: true
        type: choice
        options:
          - build-only
          - build-and-deploy
        default: build-and-deploy

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: [nuc-apps-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        working-directory: apps/spring-service
        run: ./gradlew test

  build-docker:
    name: Build Docker Image
    runs-on: [snuc-apps-runner]
    needs: run-tests
    environment: ${{ github.event.inputs.environment || 'test' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Populate properties file
        working-directory: apps/spring-service
        run: |
          RESOURCES_DIR="/opt/nuc-apps/spring-service/resources"
          PROPERTIES_FILE="application-${{ github.event.inputs.environment || 'test' }}.properties"
          
          echo "Copying '$PROPERTIES_FILE' from spring-service into directory: $RESOURCES_DIR on host machine, outside of Docker"
          cp "./src/main/resources/$PROPERTIES_FILE" "$RESOURCES_DIR/$PROPERTIES_FILE"

          chown sonic:sonic -R "$RESOURCES_DIR"
          chmod 600 "$RESOURCES_DIR/$PROPERTIES_FILE"

          sed -i "s|\${POSTGRES_DB}|${{ vars.POSTGRES_DB }}|g" "$RESOURCES_DIR/$PROPERTIES_FILE"
          sed -i "s|\${POSTGRES_USER}|${{ vars.POSTGRES_USER }}|g" "$RESOURCES_DIR/$PROPERTIES_FILE"
          sed -i "s|\${POSTGRES_PASSWORD}|${{ secrets.POSTGRES_PASSWORD }}|g" "$RESOURCES_DIR/$PROPERTIES_FILE"

      - name: Docker build
        working-directory: apps/spring-service
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          echo "Building version: $VERSION"
          docker build -t spring-service:${VERSION} .

      - name: Clean workspace
        run: |
          echo "Cleaning up workspace $GITHUB_WORKSPACE"
          rm -rf "$GITHUB_WORKSPACE"/*

  deploy:
    name: Start Docker Container
    runs-on: [nuc-apps-runner]
    needs: [run-tests, build-docker]
    if: ${{ github.event.inputs.action == 'build-and-deploy' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker compose stop
        working-directory: apps/spring-service
        run: |
          docker compose stop spring-service || true
          docker compose rm -f spring-service || true

      - name: Docker compose up
        working-directory: apps/spring-service
        env:
          COMMIT: ${{ github.sha }}
          VERSION: ${{ github.ref_name }}
          ENVIRONMENT: ${{ github.event.inputs.environment || 'test' }}
        run: |
          echo "Deploying version '$VERSION' to environment '$ENVIRONMENT'"
          echo "Commit sha '${COMMIT}'"
          docker compose up -d --build spring-service
